# Generated by Django 3.0.5 on 2021-02-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210214_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'CREDITED'), (2, 'DEBITED')]),
        ),
    ]
